# Generated by Django 4.2.6 on 2023-10-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_genre_role_studio_remove_movie_year_movie_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
