# Generated by Django 4.2.6 on 2023-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_alter_genre_id_alter_genre_moviesfk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='creditsfK',
            field=models.ManyToManyField(through='movieApp.MovieCredit', to='movieApp.person'),
        ),
    ]
