# Generated by Django 4.2.6 on 2023-10-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_genre_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rolefK',
        ),
    ]
