# Generated by Django 4.2.6 on 2023-10-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_alter_movie_creditsfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movieApp.role'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='creditsfK',
            field=models.ManyToManyField(to='movieApp.person'),
        ),
        migrations.DeleteModel(
            name='MovieCredit',
        ),
    ]
