# Generated by Django 4.2.6 on 2023-10-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_person_role_alter_movie_creditsfk_delete_moviecredit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='creditsfK',
            new_name='peoplefK',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='role',
            new_name='rolefK',
        ),
    ]
