# Generated by Django 4.2.6 on 2023-10-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0006_alter_movie_description_alter_movie_img_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
